# Social auth
SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY = '75aqwaq63u5ul4'
SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET = 'DkqAda9IgVV29qhZ'

SOCIAL_AUTH_GITHUB_KEY = 'ae6bfc9e667c8759986e'
SOCIAL_AUTH_GITHUB_SECRET = '04d159d7180f341991b151bbf76d366bd8fefafd'

SOCIAL_AUTH_BITBUCKET_KEY = 'cX7Yys6F66BBkNmMRN'
SOCIAL_AUTH_BITBUCKET_SECRET = 'qrYAkL5TTtFybS4m4CbgjTsV4Tndzbph'

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.zoho.com'
EMAIL_PORT = '587'
EMAIL_HOST_USER = 'noreply@hacklaunch.com'
EMAIL_HOST_PASSWORD = '@BGI3$*M4Yb73UpRv8g7LZ^Dxi0u%N'
DEFAULT_FROM_EMAIL = 'noreply@hacklaunch.com'
EMAIL_USE_TLS = True

# todo debug production
# AWS settings
AWS_S3_ACCESS_KEY_ID = 'AKIAIOADMUDCMHF2C5IA'
AWS_S3_SECRET_ACCESS_KEY = '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'
